#! /usr/bin/bash
export LC_COLLATE=C
shopt -s extglob
#define colors
d=`tput setab 0 setaf 7`
r=`tput setab 1 setaf 7`
b=`tput setab 4 setaf 7`
gr=`tput setab 8 setaf 7`
g=`tput setab 2 setaf 7` 
#clear screan
clear
#make sure you're in the right place
if [ -d $HOME/DB ];then
	cd $HOME/DB
else
	mkdir $HOME/DB
	cd $HOME/DB
fi
#change opening menu prompt to current PWD
PS3="${gr}PWD $PWD
please choose operation >>${d}"

#make openig menu
select DB_option in "Create DB" "Connect to DB" "List DB" "Drop DB" "Exit"
do
	PS3="${gr}PWD $PWD
please choose operation >>${d}"
	case $REPLY in
		#Create DB
		1)
			clear
			#read DB name
			read -p "${gr}Please enter DB name: ${d}" DB_name
			#validate name
			while true
			do
				case $DB_name in 
					@([A-Za-z])*([A-Za-z0-9" ""_"]) ) 
						#check if DB already exists			
						if [ -e $DB_name ];then
							clear
							echo "${r}This DB already exists${d}"
							read -p "${gr}Please enter DB name: ${d}" DB_name
						else
						#create DB directory
							mkdir $DB_name
							clear
							echo "${g}$DB_name DB created${d}"
							break
						fi
					;;
					*)
						clear
						echo "${r}DB name can only start with a char & can only contain chars, under_score or number${d}"
						read -p "${gr}Please enter DB name: ${d}" DB_name
				esac
			done	
		;;
		#Connect to DB		
		2)
			clear
			#change prompt
			PS3="${gr}please choose DB to connect to: ${d}" 
			#check whether DBs exist 
			available_DB=( `ls $PWD` )
			len=${#available_DB[@]} 
			if (( $len != 0 ));then
				#view list of available DBs to choose between
				clear
				select Current_DB in ${available_DB[@]} "Return"
				do
					case $REPLY in
						#make sure to choose of the available DBs
						[1-$len] )
							#cd to choosen DB and redirect to tabels file
							cd ./$Current_DB
							clear	
							source tables $Current_DB
							break
						;;
						$(($len+1)) )
							clear; break
						;;
						*)
							clear
							echo "${r}please choose between displayed DBs${d}"
					esac
					REPLY=	
				done
			else
				clear
				echo "${r}no available DBs${d}"	
			fi
			PS3="${gr}PWD $PWD
please choose operation >>${d}"	
		;;
		
		#LISt DB
		3)
			clear
			#check whether DBs exist
			available_DB=( `ls $PWD` )
			len=${#available_DB[@]}
			if (( $len != 0 ));then
				#list available DBs
				echo "${g}available DBs${b}"
				ls -F | grep / 
				echo "${d}"
			else
				echo "${r}No available DBs${d}"		
			fi
		;;
		#Drop DB
		4) 
			clear
			#check whether DBs exist
			available_DB=( `ls $PWD` )
			len=${#available_DB[@]}
			if (( $len != 0 ));then
				PS3="${gr}please choose drop mode : ${d}"
				#select to drop all or just one
				select op in "Drop all" "Drop one" "Return"
				do
					#make sure to choose of the available options
					case $REPLY in 
						1)
							clear
							for DB in ${available_DB[@]}
							do
								rm -r $DB
							done
							echo "${g}all DBs removed${d}"
							break
						;;
						2)
							clear
							PS3="${gr}please choose DB to drop : ${d}"
							select Current_DB in ${available_DB[@]} "Return"
							do
								#make sure to choose of the available DBs
								case $REPLY in
									[1-$len] )
										rm -r ./$Current_DB
										clear
										echo "${g}$Current_DB DB removed${d}"
										break
									;;
									$(($len+1)) )
										clear; break
									;;	
									*)
										clear
										echo "${r}please choose between displayed DBs${d}" 
								esac	
								REPLY=			
							done
							break
						;;
						3)
							clear; break
						;;
						*)
							clear
							echo "${r}Please choose from available modes${d}"
					esac
					REPLY=
				done	
			else
				clear
				echo "${r}No available DBs${d}"
			fi
			PS3="${gr}PWD $PWD
please choose operation >>${d}"
		;;
		#Exit
		5) 
			clear; exit
		;;

		#default
		*)
			clear 
			echo "${r}Please choose from available operations${d}"
	esac
	REPLY=
done


