#! /usr/bin/bash
export LC_COLLATE=C
shopt -s extglob 
#define colors
d=`tput setab 0 setaf 7`
r=`tput setab 1 setaf 7`
b=`tput setab 4 setaf 7`
gr=`tput setab 8 setaf 7`
g=`tput setab 2 setaf 7` 

PS3="${gr}connectedd to $1 DB
please choose operation >>${d}"

select table_option in "Create table" "List tables" "Drop table" "Insert into table" "Select from table" "Delete from table" "Update table" "Return" "Exit"
do
	case $REPLY in
		#Create table
		#read Table name 
		1) 
			clear
			pk=0
			read -p "${gr}Please enter Table name: ${d}" Table_name
			while true
			do
				#validate name
				case $Table_name in 
					@([A-Za-z])*([A-Za-z0-9" ""_"]) ) 
						#check if Table already exists			
						if [ -e $Table_name ];then
							clear
							echo "${r}This Table already exists${d}"
							read -p "${gr}Please enter Table name: ${d}" Table_name
						else
							#read column name,constrain and data type
							while true
							do
								read -p "${gr}Please enter column number: ${d}" Column_number
								case $Column_number in
									@([1-9])*([1-9]) )
										break
									;;
									*)
										clear
										echo "${r}please enter a number${d}"	
								esac
							done
							for ((i=1; i <= $Column_number; i++))
							do
								clear
								read -p "${gr}Please enter column no.$i name: ${d}" Column_name
								
								while true
								do
									#validate name
									case $Column_name in 
										@([A-Za-z])*([A-Za-z0-9" ""_"]) ) 
											for name in ${column_arr[@]}
											do
												#check if column name already exist
												while true
												do
													if [[ $Column_name == $name ]];then
														clear
														echo "${r}this column already exists${d}"
														read -p "${gr}Please enter column no.$i name: ${d}" Column_name
														while true
														do
															case $Column_name in 
																@([A-Za-z])*([A-Za-z0-9" ""_"]) ) 
																	break
																;;
																*)
																	clear
																	echo "${r}Column name can only start with a char & can only contain chars, under_score or number ${d}"
																	read -p "${gr}Please enter column no.$i name: ${d}" Column_name
															esac
														done
													else
														break
													fi
												done			
												
											done											
											clear		
											PS3="${gr}Please choose column no.$i constraint: ${d}"
											#make sure only one PK
											if (( $pk == 0 ));then
												select column_constrain in "Primary-Key" "Unique" "None"
												do
													case $REPLY in
														1)
															const="PK"
															pk=1
															break
														;;
														2)
															const="UN"
															break
														;;
														3)
															const="NO"
															break
														;;
														*)
															clear
															echo "${r}please choose between displayed constrains${d}"  
													esac
													REPLY=	
												done
											else
												select column_constrain in "Unique" "None"
												do
													case $REPLY in
														1)
															const="UN"
															break
														;;
														2)
															const="NO"
															break
														;;
														*)
															clear
															echo "${r}please choose between displayed constrains${d}"  
													esac
													REPLY=	
												done
											fi
											clear	
											PS3="${gr}Please choose column no.$i data type: ${d}"
											select column_constrain in "String" "Integer"
											do
												case $REPLY in
													1)
														type="str"
														break
													;;
													2)
														type="int"
														break
													;;
													*)
														clear
														echo "${r}please choose between displayed data types${d}"  
												esac
												REPLY=	
											done	
											#create file for data and another hidden for meta_data
											touch .$Table_name
											touch $Table_name
											column_arr+=($Column_name)
											echo "$Column_name $const $type" >> .$Table_name
											break
										;;
										*)
											clear
											echo "${r}Column name can only start with a char & can only contain chars, under_score or number ${d}"
											read -p "${gr}Please enter column no.$i name: ${d}" Column_name
									esac
								done
							done
							clear	
							echo "${g}$Table_name table created${d}"
							break
						fi
						# col_arr=(${column_arr[@]})
						column_arr=()
					;;
					*)
						clear
						echo "${r}Table name can only start with a char & can only contain chars, under_score or number ${d}"
						read -p "${gr}Please enter Table name: ${d}" Table_name
				esac	
			done
			PS3="${gr}connected to $1 DB
please choose operation >>${d}"
		;;
		#LISt tables
		2)
			clear
			#check whether Tables exist
			available_Tables=( `ls $PWD` )
			len=${#available_Tables[@]}
			if (( $len != 0 ));then
				echo "${g}available tables${b}"
				ls 
				echo "${d}"
			else
				echo "${r}no available tables${d}"		
			fi
		;;
		#Drop table
		3) 
			clear
			#check whether tables exist
			PS3="${gr}Please choose delete mode: ${d}"
			available_Tables=( `ls $PWD` )
			len=${#available_Tables[@]}
			if (( $len != 0 ));then
				select op in "Drop all" "Drop one" "Return"
				do
					#make sure to choose of the available options
					case $REPLY in 
						1)
							clear
							for Table in ${available_Tables[@]}
							do
								rm -r $Table
								find . -type f -name ".*" -delete
							done
							echo "${g}all tables removed${d}"
							break
						;;
						2)
							clear
							PS3="${gr}please choose table to drop : ${d}"
							select Current_Table in ${available_Tables[@]} "Return"
							do
								#make sure to choose of the available Tables
								case $REPLY in
									[1-$len] )
										rm -r $Current_Table
										find . -type f -name ".*" -delete
										clear
										echo "${g}$Current_Table table removed${d}"
										break
									;;
									$(($len+1)) )
										clear; break
									;;
									*)
										clear
										echo "${r}please choose between displayed tables${d}" 
								esac
								REPLY=				
							done	
							break
						;;
						3)
							clear; break
						;;
						*)
							clear
							echo "${r}Please choose from available modes${d}"
					esac
					REPLY=
				done	
			else
				clear
				echo "${r}No available tables${d}"
			fi
			PS3="${gr}connected to $1 DB   
please choose operation >>${d}"
		;;
		#insert into table
		4)
			clear
			counter=1
			PS3="${gr}please choose Table to insert into: ${d}"
			available_Tables=( `ls $PWD` )
			len=${#available_Tables[@]}
			if (( $len == 0 ));then
				echo "${r}No available tables${d}"
			else
				select Current_Table in ${available_Tables[@]} "Return"
				do		
					#make sure to choose of the available Tables
					clear
					case $REPLY in
						[1-$len] )
							col=(`cut -d ' ' -f 1 .$Current_Table`)
							for col_val in ${col[@]}
							do
								read -p "${gr}please enter $col_val: ${d}" entry 
								type=`awk -F' ' '{
									if($1==c){
										print $3
										}										
									}' c=$col_val .$Current_Table`
								const=`awk -F' ' '{
									if($1==c){
										print $2
										}										
									}' c=$col_val .$Current_Table`
								while true
								do
									#constrain check
									if [[ $const != "NO" ]];then
										var=`awk -F' ' '{
											if($c==e){
												print e
												}										
											}' e=$entry c=$counter $Current_Table`	
										if [[ $var == "" ]];then
											if [[ $type == "int" ]];then	
												if [[ $entry =~ [[:digit:]]+ ]];then										 
													break
												else
													clear
													echo "${r}please enter a number${d}"
													read -p "${gr}please enter $col_val: ${d}" entry
												fi
											else
												if [[ $entry =~ [[:alpha:]]+ ]];then										
													break
												else
													clear
													echo "${r}please enter a string${d}"
													read -p "${gr}please enter $col_val: ${d}" entry
												fi
											fi
										else
											clear
											echo "${r}this entry already exist${d}"
											read -p "${gr}please enter $col_val: ${d}" entry
										fi
									else
										if [[ $type == "int" ]];then	
												if [[ $entry =~ [[:digit:]]+ ]];then										
													break
												else
													clear
													echo "${r}please enter a number${d}"
													read -p "${gr}please enter $col_val: ${d}" entry
												fi
											else
												if [[ $entry =~ [[:alpha:]]+ ]];then										
													break
												else
													clear
													echo "${r}please enter a string${d}"
													read -p "${gr}please enter $col_val: ${d}" entry
												fi
											fi
									fi
								done
								entries_arr+=$entry' '  
								counter=$(($counter+1))	
							done
							echo ${entries_arr[@]} >> $Current_Table
							entries_arr=()
							clear
							echo "${g}Entry recorded${d}"
							break
						;;
							$(($len+1)) )
								clear; break
						;;
						*)
							clear
							echo "${r}please choose between displayed tables${d}" 
					esac
					REPLY=
				done
			fi
			PS3="${gr}connected to $1 DB   
please choose operation >>${d}"
		;;
		#select from table
		5)
		# in the select all try to show column names
			clear
			PS3="${gr}please choose Table to select from: ${d}"
			available_Tables=( `ls $PWD` )
			len=${#available_Tables[@]}
			if (( $len == 0 ));then
				clear
				echo "${r}No available tables${d}"
			else
				select Current_Table in ${available_Tables[@]} "Return"
				do
					#make sure to choose of the available Tables
					case $REPLY in
						[1-$len] )
							if [[ `cat $Current_Table` == "" ]];then
								clear
								echo "${r}Table is empty${d}" 
								break
							else
								clear
								PS3="${gr}please choose select mode: ${d}"
								select mode in "Select all" "Select by column" "Select by record" "Return"
								do
									case $REPLY in	
										1)
											clear
											echo "${g}Table content${b}"
											cat $Current_Table
											echo ${d}
											break
										;;								
										2)	
											col=(`cut -d ' ' -f 1 .$Current_Table`)
											col_len=${#col[@]}
											clear
											PS3="${gr}please choose column: ${d}"
											select col in ${col[@]} "Return"
											do	
												case $REPLY in
													[1-$col_len] )
														clear
														echo "${g}col $col${b}"
														awk -F' ' -v var=$REPLY '{
															print $var
															}
															' $Current_Table
														echo ${d}
														break
													;;
													$(($col_len+1)) )
														clear; break
													;;
													*)
														clear
														echo "${r}please choose between displayed columns${d}"
												esac
												REPLY=	
											done
											break
										;;
										3)
											col=(`cut -d ' ' -f 1 .$Current_Table`)
											col_len=${#col[@]}
											clear
											PS3="${gr}please choose column: ${d}"
											select col in ${col[@]} "Return"
											do	
												case $REPLY in
													[1-$col_len] )
														clear
														read -p "${gr}Please enter value of $col: ${d}" value
														var=`awk -F' ' 'BEGIN{x=0}{
															if($c==v){
																print $0
																x=1
																}
															}
															END{if(x==0)print "No match"}' l=$col_len c=$REPLY v=$value $Current_Table`
														if [[ $var == 'No match' ]];then
															clear
															echo "${r}No match${d}"
														else
															clear
															echo "${g}Retrieved record${d}"
															echo "${b}$var${d}" 
														fi
														break
													;;
													$(($col_len+1)) )
														clear; break
													;;
													*)
														clear
														echo "${r}please choose between displayed columns${d}"
												esac
												REPLY=	
											done
											break
										;;
										4)
											clear; break
										;;
										*)
											clear
											echo "${r}please choose 1-3${d}" 
									esac
									REPLY=
								done
								break
							fi
						;;
						$(($len+1)) )
							clear; break
						;;
						*)
							clear
							echo "${r}please choose between displayed tables${d}" 
					esac
					REPLY=
				done
			fi
			PS3="${gr}connected to $1 DB   
please choose operation >>${d}"
		;;
		#delete from table
		6)
			clear
			PS3="${gr}please choose Table to delete from: ${d}"
			available_Tables=( `ls $PWD` )
			len=${#available_Tables[@]}
			if (( $len == 0 ));then
				echo "${r}No available tables${d}"
			else
				select Current_Table in ${available_Tables[@]} "Return"
				do
					#make sure to choose of the available Tables
					case $REPLY in
						[1-$len] )
							if [[ `cat $Current_Table` == "" ]];then
								clear
								echo "${r}Table is empty${d}" 
								break
							else
								clear
								PS3="${gr}please choose delete mode: ${d}"
								select mode in "Delete all" "Delete by record" "Return"
								do
									case $REPLY in	
										1)
											sed -ni '/^*/d' $Current_Table
											clear
											echo "${g}Table content deleted${d}"
											break
										;;								
										2)
											col=(`cut -d ' ' -f 1 .$Current_Table`)
											col_len=${#col[@]}
											clear
											PS3="${gr}please choose column: ${d}"
											select col in ${col[@]} "Return"
											do	
												case $REPLY in
													[1-$col_len] )
														clear
														read -p "${gr}Please enter value of $col to delete its entry: ${d}" value
														var=`awk -F' ' 'BEGIN{x=0}{
															if($c==v){
																line=$0
																print line
																x=1
																}
															}
															END{if(x==0)print "No match"}' l=$col_len c=$REPLY v=$value $Current_Table`
														sed -i "/$var/d" $Current_Table
														if [[ $var == 'No match' ]];then
															clear
															echo "${r}No match${d}"
														else
															clear
															echo "${g}Entry deleted${d}" 
														fi
														break
													;;
													$(($col_len+1)) )
														clear; break
													;;
													*)
														clear
														echo "${r}please choose between displayed columns${d}"
												esac
												REPLY=	
											done
											break
										;;
										3)
											clear; break
										;;
										*)
											clear
											echo "${r}please choose 1-2${d}" 
									esac
									REPLY=
								done
								break
							fi
						;;
						$(($len+1)) )
							clear; break
						;;
						*)
							clear
							echo "${r}please choose between displayed tables${d}" 
					esac
					REPLY=
				done
			fi
			PS3="${gr}connected to $1 DB   
please choose operation >>${d}"
		;;
		#update table
		7)
			clear
			# col_len=${#col_arr[@]}
			PS3="${gr}please choose Table to delete from: ${d}"
			available_Tables=( `ls $PWD` )
			len=${#available_Tables[@]}
			if (( $len == 0 ));then
				echo "${r}No available tables${d}"
			else
				select Current_Table in ${available_Tables[@]} "Return"
				do
					#make sure to choose of the available Tables
					case $REPLY in
						[1-$len] )
							if [[ `cat $Current_Table` == "" ]];then
								clear
								echo "${r}Table is empty${d}" 
								break
							else
								clear
								col=(`cut -d ' ' -f 1 .$Current_Table`)
								col_len=${#col[@]}
								clear
								PS3="${gr}please choose column: ${d}"
								select col in ${col[@]} "Return"
								do	
									case $REPLY in
										[1-$col_len] )
											clear
											read -p "${gr}Please enter value of $col to update: ${d}" replace
											read -p "${gr}Please enter new value of $col: ${d}" new
											type=`awk -F' ' '{
												if($1==c){
													print $3
													}										
												}' c=$col .$Current_Table`
											const=`awk -F' ' '{
												if($1==c){
													print $2
													}										
												}' c=$col .$Current_Table`
											while true
											do
												#constrain check
												if [[ $const != "NO" ]];then
													var=`awk -F' ' '{
														if($c==e){
															print e
															}										
														}' e=$new c=$REPLY $Current_Table`	
													if [[ $var == "" ]];then
														if [[ $type == "int" ]];then	
															if [[ $new =~ [[:digit:]]+ ]];then							
																break
															else
																clear
																echo "${r}please enter a number${d}"
																read -p "${gr}Please enter new value of $col: ${d}" new
															fi
														else
															if [[ $new =~ [[:alpha:]]+ ]];then							
																break
															else
																clear
																echo "${r}please enter a string${d}"
																read -p "${gr}Please enter new value of $col: ${d}" new
															fi
														fi
													else
														clear
														echo "${r}this entry already exist${d}"
														read -p "${gr}please enter $col_val: ${d}" new
													fi
												else
													if [[ $type == "int" ]];then	
														if [[ $new =~ [[:digit:]]+ ]];then							
															break
														else
															clear
															echo "${r}please enter a number${d}"
															read -p "${gr}Please enter new value of $col: ${d}" new
														fi
													else
														if [[ $new =~ [[:alpha:]]+ ]];then							
															break
														else
															clear
															echo "${r}please enter a string${d}"
															read -p "${gr}Please enter new value of $col: ${d}" new
														fi
													fi
												fi
											done
											var1=`awk -F' ' '{
												if($c==r){
													print $0
													}										
												}' n=$new c=$REPLY r=$replace $Current_Table`
											var2=`awk -F' ' '{
												if($c==r){
													$c=n
													print $0
													}										
												}' n=$new c=$REPLY r=$replace $Current_Table`
											if [[ $var1 != "" ]];then
												clear
												sed -i "s/$var1/$var2/g" $Current_Table	
												echo "${g}entry updated${d}"
											else
												clear
												echo "${r}No match${d}" 
											fi
											break
										;;
											$(($col_len+1)) )
												clear; break
										;;
										*)
											clear
											echo "${r}please choose between displayed columns${d}"
									esac
									REPLY=	
								done
								break
							fi 
						;;
						$(($len+1)) )
							clear; break
						;;
						*)
							clear
							echo "${r}please choose between displayed tables${d}" 
					esac
					REPLY=
				done
			fi
			PS3="${gr}connected to $1 DB   
please choose operation >>${d}"
		;;
		8)
			clear; break
		;;
		#Exit
		9) 
			clear; exit
		;;
		#Default
		*) 
			clear
			echo "${r}Please enter a number between 1-8${d}"
	esac
	REPLY=
done
